<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: 'Helvetica', sans-serif; margin: 0; padding: 0; }
        /* The Gold Bar from your design */
        .gold-bar { background-color: #d4af23; height: 15px; width: 100%; position: absolute; top: 0; }
        
        .header { text-align: center; margin-top: 40px; }
        .header h1 { margin: 0; font-size: 26px; color: #0f172a; }
        .header p { margin: 2px; font-size: 10px; color: #666; }
        
        .gold-line { border-bottom: 1px solid #d4af23; margin: 20px 40px; }

        .report-title { margin-left: 40px; font-size: 18px; font-weight: bold; }
        .report-info { margin-left: 40px; font-size: 10px; color: #555; margin-bottom: 20px; }

        /* Summary Box from your design */
        .summary-box { 
            margin: 0 40px; background-color: #f8f9fa; border: 1px solid #ddd; padding: 15px;
        }
        .summary-line { font-family: 'Courier', monospace; font-size: 12px; margin-bottom: 5px; }
        .total-line { border-top: 2px solid #d4af23; padding-top: 5px; font-weight: bold; font-size: 14px; }

        /* Transactions Table */
        table { width: 90%; margin: 20px auto; border-collapse: collapse; font-size: 10px; }
        th { background-color: #282828; color: white; padding: 8px; text-align: left; }
        td { padding: 8px; border-bottom: 1px solid #eee; }
        
        /* Watermark logic */
        .watermark {
            position: fixed; top: 30%; left: 10%; width: 100%; text-align: center;
            opacity: 0.05; font-size: 60px; transform: rotate(-45deg); z-index: -1000;
            font-weight: bold; color: #000;
        }
    </style>
</head>
<body>
    <div class="watermark">CORNERSTONE</div>
    <div class="gold-bar"></div>

    <div class="header">
        <h1>CORNERSTONE CHURCH</h1>
        <p>123 Church Lane, City Name, Philippines</p>
        <p>Contact: (02) 888-7000 | Email: info@cornerstonechurch.org</p>
    </div>

    <div class="gold-line"></div>

    <div class="report-title">FINANCIAL OVERVIEW REPORT</div>
    <div class="report-info">
        Report Period: {{ $reportDate }}<br>
        Generated by: System Administrator
    </div>

    <div class="summary-box">
        <div class="summary-line">Total Income:   -------------------- ₱{{ number_format($income, 2) }}</div>
        <div class="summary-line">Total Expenses: -------------------- ₱{{ number_format($expense, 2) }}</div>
        <div class="summary-line total-line">NET FUND BALANCE:  ---------------- ₱{{ number_format($balance, 2) }}</div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Ref ID</th>
                <th>Description</th>
                <th>Type</th>
                <th>Date</th>
                <th>Amount</th>
            </tr>
        </thead>
        <tbody>
            @foreach($transactions as $tnx)
            <tr>
                <td>TXN-{{ $tnx->Transaction_Id }}</td>
                <td>{{ $tnx->Description }}</td>
                <td>{{ $tnx->Type }}</td>
                <td>{{ $tnx->Transaction_Date }}</td>
                <td style="text-align: right;">₱{{ number_format($tnx->Amount, 2) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
</body>
</html>